### ISSUE TITLE
add 009-129.yaml

### ISSUE THREAD

**Issue by marco-hacs** [oyvindwe/connectlife-ha#113]
Thank you for the splendid work... I added 009-129 which was not in the work.
The starting base was 009-109 but my air conditioner has a smart eye that wants them swing with ai and the air purifier. If my work is helpful you could fix the names.
thank you

```
climate:
  presets:
    - preset: eco
      t_power: 1
      t_eco: 1
      t_fan_speed: 0 # auto
    - preset: ai
      t_power: 1
      t_tms: 1
properties:
#####################################


  - property: daily_energy_kwh
    hide: true
    sensor:
      state_class: total
      device_class: energy
      unit: kWh

  - property: f_votage
    sensor:
      device_class: voltage
      unit: V


  - property: t_purify
    icon: mdi:air-purifier
    switch:
      device_class: switch

  - property: t_swing_follow
    icon: mdi:account-arrow-right
    select:
      options:
        0: "Off"
        1: Follow
        2: Not Follow

  - property: f_cool_qvalue
    sensor:
      unit: BTU/hr
      state_class: measurement

  - property: f_heat_qvalue
    icon: mdi:weather-sunny
    sensor:
      unit: BTU/hr



############################
  - property: f_temp_in
    climate:
      target: current_temperature
  - property: t_beep
    switch: {}
  - property: t_eco
    icon: mdi:leaf
    switch:
      device_class: switch
  - property: t_fan_mute
    switch: {}
  - property: t_fan_speed
    climate:
      target: fan_mode
      options:
        0: auto
        5: low
        6: middle_low
        7: medium
        8: middle_high
        9: high
  - property: f_humidity
    climate:
      target: current_humidity
      unknown_value: 128
  - property: t_power
    climate:
      target: is_on
  - property: t_sleep
    icon: mdi:sleep
    select:
      options:
        0: "off"
        1: general
        2: for_old
        3: for_young
        4: for_kid
  - property: t_super
    icon: mdi:run-fast
    switch:
      device_class: switch
  - property: t_swing_angle
    icon: mdi:arrow-oscillating
    select:
      options:
        0: swing
        1: auto
        2: angle_1
        3: angle_2
        4: angle_3
        5: angle_4
        6: angle_5
        7: angle_6
  - property: t_swing_direction
    climate:
      target: swing_mode
      options:
        0: forward
        1: right
        2: swing
        3: both_sides
        4: left
  - property: t_temp
    climate:
      target: target_temperature
      min_value:
        celsius: 16
        fahrenheit: 61
      max_value:
        celsius: 32
        fahrenheit: 90
  - property: t_temp_type
    climate:
      target: temperature_unit
      options:
        0: celsius
        1: fahrenheit
  - property: t_tms
    switch:
      device_class: switch
  - property: t_work_mode
    climate:
      target: hvac_mode
      options:
        0: fan_only
        1: heat
        2: cool
        3: dry
        4: auto
```

On homeassistant it looks like this.

![image](https://github.com/user-attachments/assets/e9fe21b1-2760-4919-a71b-06c8961e3f69)
