### ISSUE TITLE
Howto start dishwasher

### ISSUE THREAD

**Issue by Marcelh1** [oyvindwe/connectlife-ha#181]
Any instruction how to start dishwasher is more than welcome :)
I know where to find "**ConnectLife: Set value**", but which entity to set?

**Comment by oyvindwe** [comment]
Due to safety regulations, you can only remote start appliances after enabling remote start physically on the appliance for each run.

Which property to set depends on the model. I haven't bothered to figure out that on my own dishwasher.

**Comment by Marcelh1** [comment]
Yes I know, since I also have the connectlife App. How will I be able to figure out what I need to do te perform a remote start?

**Comment by oyvindwe** [comment]
I'd say you are on the right track. I'm not sure why you get that error message.

Which device is you dishwasher? In the mapping file, you can try to make the property a switch, e.g. if the property name is `Child_lock`, and "off" value is 1:
```
- property: Child_lock
  unavailable: 0
  switch:
    "off": 1
    "on": 2
```

Some devices have write-only properties to set state. You can also try:
```
- property: Child_lock
  unavailable: 0
  switch:
    "off": 1
    "on": 2
    command:
      name: Child_lock_cmd
      adjust: 1              # This will send 0 to disable and 1 to enable - remove to send 1 to disable and 2 to enable
```
