### ISSUE TITLE
How do you set odor control for 015-000?

### ISSUE THREAD

**Issue by TheSimpleZ** [oyvindwe/connectlife-ha#189]
Hello!

I saw your comment here: https://github.com/oyvindwe/connectlife-ha/issues/181#issuecomment-2566500475
That works great for the child lock. But I'd like to have something similar for the odor control setting (and other switches).
I tried writing to it using the set value action, didn't work. I also tried using `Odor_control_setting_cmd` as the command on the switch doing the same thing as for the child lock, both with and without the adjust parameter, but that didn't work either.

How do you find those write-only properties not listed in the dump file?

**Comment by Marcelh1** [comment]
Just to be sure, check if you are modifying the right file, I have a 60.3 model, so my filename is:
`/homeassistant/custom_components/connectlife/data_dictionaries/015-dishwasher-60.3.yaml`

Then I would try:

```
  - property: Odor_control_setting
    unavailable: 0
    switch:
      "off": 1
      "on": 2
      command:
        name: Odor_control_setting_cmd
        adjust: 1
```

There is also a special remark in the App (preferences) about the Odor.... not sure what is meant with that remark. Looks like you get an additional program: "Odor"? I have not checked this myself.

**Comment by TheSimpleZ** [comment]
Thanks! But yeah, I've checked. Controlling the child lock in that way works perfectly fine. And I already tried the piece of code you wrote without success. 

The remark says that there is a program called Odor Control. But to make that program available, you must enable the Odor Control setting. Essentially, that setting only makes the Odor Control program available for you to use; it does not actually run it.

**Comment by Marcelh1** [comment]
I also checked this myself, indeed, it doesn't work, strange.

**Comment by oyvindwe** [comment]
Try this for odor control:
```
  - property: Odor_control_setting
    unavailable: 0
    switch:
      "off": 1
      "on": 2
      command:
        name: Oder_control_setting
        adjust: 1
```
Seems to work on my `015-dishwasher-60.f` (previously 015-000).

I've also found out how to enable auto dose, but you have to set auto dose quantity > 0 in the same request as it is being enabled, and that's currently not supported by the integration.
