### ISSUE TITLE
Adding support for water_heater / Heat Pump

### ISSUE THREAD

**Issue by bartashevich** [oyvindwe/connectlife-ha#44]
Hi, I have Hisense Heat Pump and I managed to integrate in Home assistant by adapting code from /bilan/connectlife-api-connector. And now I'm trying to setup permanently using your code.

The thing is, bilan code uses mqtt to create entities, in which I found water_heater https://www.home-assistant.io/integrations/water_heater.mqtt/

But, I'm not being able to set it up properly using your code. Here is my configuration file so far, based on https://developers.home-assistant.io/docs/core/entity/water-heater/

File: 016-502.yaml
```
device_type: water_heater
properties:
  - property: f_water_tank_temp
    water_heater:
      target: current_temperature
  - property: t_beep
    switch: {}
  - property: t_fan_speed
    switch: {}
  - property: t_sterilization
    switch: {}
  - property: t_vacation
    switch: {}
  - property: t_temp
    water_heater:
      target: target_temperature
      min_value:
        celsius: 20
        fahrenheit: 68
      max_value:
        celsius: 65
        fahrenheit: 149
  - property: t_temp_type
    water_heater:
      target: temperature_unit
      options:
        0: celsius
        1: fahrenheit
  - property: t_work_mode
    water_heater:
      target: operation_list
      options:
        8: eco
        9: heat_pump
        11: performance
        12: electric
  - property: t_power
    water_heater:
      target: is_on
```

Full API scrape:
```
[{"wifiId":"xxxxxxxxxxx","deviceId":"yyyyyyyyyyyyy","puid":"zzzzzzzzzzz","deviceNickName":"Heat\u00a0pump","deviceFeatureCode":"502","deviceFeatureName":"502\u81ea\u7814\u70ed\u6c34\u5668","deviceTypeCode":"016","deviceTypeName":"","bindTime":1693922922378,"role":1,"roomId":2716250,"roomName":"default_room","statusList":{"t_work_mode":"9","t_power":"1","t_temp":"35","f_backwater":"0","t_backwater_set":"0","t_vacation":"0","t_air":"0","t_fan_speed":"0","t_sterilization":"0","f_sterilization":"1","t_beep":"0","t_vacation_timeset":"1","t_vacation_timeleft":"0","f_electricity":"0","f_votage":"0","f_power_consumption":"0","f_electric_heating":"0","f_heat_pump":"1","f_water_tank_temp":"60","f_e_push":"0","f_e_displaycom_fault":"0","f_e_coiltemp":"0","f_e_env_temp":"0","f_e_exhaust":"0","f_e_suctiontemp_fault":"0","f_e_solar_temperature":"0","f_e_fan_fault":"0","f_e_upwatertank_fault":"0","f_e_downwatertank_fault":"0","f_e_e2data_fault":"0","f_e_drivecom_fault":"0","f_e_drive_fault":"0","f_e_returnwatertemp_fault":"0","f_e_clockchip_fault":"0","f_e_eanode_fault":"0","f_e_powermodule_fault":"0","oem_host_version":"S1798.6.01.06.RB","daily_energy_kwh":0},"useTime":0,"offlineState":1,"seq":0,"createTime":0}]
```

I end up only with switch entities working properly. But not water_heater entity is added. Any idea?

**Comment by oyvindwe** [comment]
> But not water_heater entity is added. Any idea?

That entity type is not support yet. It is very similar to climate, so should be easy to add

**Comment by bartashevich** [comment]
Problem is that climate doesn't accept modes such as heat_pump, electric, performance:
```
  - property: t_work_mode
    water_heater:
      target: operation_list
      options:
        8: eco
        9: heat_pump
        11: performance
        12: electric
```

**Comment by bartashevich** [comment]
Ah, I understand now what you mean by not being supported. This addon doesn't have water_heater.py.

If I use climate.py as a template for water_heater.py, do you think that will be enough to make it work?

**Comment by oyvindwe** [comment]
Is the fan only on/off?

**Comment by oyvindwe** [comment]
> If I use climate.py as a template for water_heater.py, do you think that will be enough to make it work?

I'm already working on it :)

**Comment by oyvindwe** [comment]
`state` is a bit tricky to map, as it cannot be mapped 1-1. We need a new top-level mapping that can map a target property to a set of device properties. I have a similar problem with `climate.preset` that I am working on.

For now I propose to just map `t_power` to `state` and `t_eco` to a separete switch. But what is the "on" state for your heat pump? It must be one of the states here: https://developers.home-assistant.io/docs/core/entity/water-heater#states

**Comment by oyvindwe** [comment]
Also we can have self defined values for `current_operation` - or is this the correct mapping comparing with the ConnectLife app?
```yaml
  - property: t_work_mode
    water_heater:
      target: current_operation
      options:
        8: eco
        9: heat_pump
        11: performance
        12: electric
```
